version: "3.9"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      DB_CONNECTION: 'postgresql://postgres:example@postgres:5432/postgres'

  db:
    image: "postgres"
    hostname: "postgres"
    container_name: "postgres"
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"


