"""third

Revision ID: a61857c52f04
Revises: d6d9fa372ee3
Create Date: 2022-09-24 11:44:21.162256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a61857c52f04'
down_revision = 'd6d9fa372ee3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
