"""first

Revision ID: 4b753f71b499
Revises: 
Create Date: 2022-09-03 12:02:28.621111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b753f71b499'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('currency_name', sa.String(length=35), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('currency',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('currency_name', sa.String(), nullable=False),
    sa.Column('cost_to_one_usd', sa.Integer(), nullable=False),
    sa.Column('available_quantity', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=12), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deposite',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('opening_date', sa.Text(), nullable=False),
    sa.Column('closing_date', sa.Text(), nullable=False),
    sa.Column('balance', sa.Numeric(), nullable=False),
    sa.Column('interest_rate', sa.Numeric(), nullable=False),
    sa.Column('storage_conditions_which_account_id', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rating',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('currency_name', sa.String(length=30), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, foreign_key=True),
    sa.Column('type_of_transaction', sa.String(), nullable=False),
    sa.Column('amount_of_currency', sa.Numeric(), nullable=False),
    sa.Column('currency_with_which_the_transaction', sa.String(), nullable=False),
    sa.Column('currency_in_which_the_transaction', sa.String(), nullable=False),
    sa.Column('data_time', sa.String(), nullable=False),
    sa.Column('amount_of_currency_received', sa.Numeric(), nullable=False),
    sa.Column('commission', sa.Numeric(), nullable=False),
    sa.Column('account_id_from_which_the_transaction', sa.String(), nullable=False),
    sa.Column('account_id_on_which_the_transaction', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('transaction_history')
    op.drop_table('rating')
    op.drop_table('deposite')
    op.drop_table('currency')
    op.drop_table('account')
    # ### end Alembic commands ###
